- hosts: localhost
  gather_facts: no

  tasks:
  - name: create vm
    esxissh_guest:
      esxiaddress: '{{ esxiaddr }}'
      esxiusername: '{{ esxiuser }}'
      esxipassword: '{{ esxipass }}'
      name: vm-example
      guest_id: centos7-64  # API使用時と書式違うので注意
      datastore: WDS100T2B0A
      hardware:
        memory_mb: 4096
        num_cpus: 2
      networks:
        - name: VM Network
          device_type: vmxnet3
      disk:
        - size_gb: 10
          type: thin
      cdrom:
        - type: iso
          iso_path: cheddar-share/disk2/archive/iso/CentOS-7-x86_64-Minimal-1908.iso
      state: present
