- hosts: localhost
  gather_facts: no

  tasks:
  - name: create vm
    zaki_lknr.esxissh.esxissh_guest:
      esxiaddress: '{{ esxiaddr }}'
      esxiusername: '{{ esxiuser }}'
      esxipassword: '{{ esxipass }}'
      name: vm-example
      guest_id: centos7_64Guest
      datastore: WDS100T2B0A
      hardware:
        memory_mb: 4096
        num_cpus: 2
      networks:
        - name: VM Network
          device_type: vmxnet3
        - name: private-network-1
          device_type: vmxnet3
      disk:
        - size_gb: 10
          type: thin
        # - size_gb: 3
        #   type: eagerzeroedthick
      cdrom:
        - type: iso
          iso_path: cheddar-share/disk2/archive/iso/CentOS-7-x86_64-Minimal-1908.iso
        - type: iso
          iso_path: cheddar-share/disk2/archive/iso/CentOS-8.2.2004-x86_64-minimal.iso
      state: present
