- hosts: localhost
  gather_facts: no

  tasks:
  - name: delete vm
    zaki_lknr.esxissh.esxissh_guest:
      esxiaddress: '{{ esxiaddr }}'
      esxiusername: '{{ esxiuser }}'
      esxipassword: '{{ esxipass }}'
      name: vm-example
      guest_id: centos7_64Guest
      datastore: WDS100T2B0A
      state: absent
