- hosts: localhost
  gather_facts: no

  tasks:
  - name: power_on
    esxissh_guest_power:
      esxiaddress: '{{ esxiaddr }}'
      esxiusername: '{{ esxiuser }}'
      esxipassword: '{{ esxipass }}'
      vmname: vm-example
      state: poweron
